namespace GamepadMapper.Configuration
{
    public enum InputKey
    {
        A,
        B,
        X,
        Y,
        DPadLeft,
        DPadUp,
        DPadRight,
        DPadDown,
        LB,
        RB,
        LT,
        RT,
        Back,
        Start,
        LSB,
        RSB,
        ModA,
        ModB,
        ModX,
        ModY,
        ModDPadLeft,
        ModDPadUp,
        ModDPadRight,
        ModDPadDown,
        ModLB,
        ModRB,
        ModLT,
        ModRT,
        ModBack,
        ModStart,
        ModLSB,
        ModRSB
    }
}